---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zgroup
spec:
  selector:
    matchLabels:
      app: zgroup
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: zgroup
    spec:
      containers:
      - name: zgroup
        image: quay.io/flowerinthenight/zgroup:v0.1.0
        command: ["/bin/sh"]
        args: ["-c", '/app/zgroup group1 ${K8S_MY_POD_IP}:8080']
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 100m
            memory: 500Mi
        imagePullPolicy: Always
        env:
        # Downward value to know if we are running in k8s.
        - name: K8S_MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zgroup-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zgroup
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 40
