name: main

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  codeberg:
    name: Codeberg
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: "https://codeberg.org/flowerinthenight/zgroup.git"
          GIT_USERNAME: flowerinthenight
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}

  build:
    name: Build
    if: "!contains(github.event.commits[0].message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - name: Print GH context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Run tests
        run: zig build test

      - name: Release from tags
        if: startsWith(github.event.ref, 'refs/tags/v')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          zig build -Doptimize=ReleaseFast -Dtarget=x86_64-linux --summary all
          cp zig-out/bin/zgroup ./
          tar czvf zgroup-${GITHUB_REF_NAME}-x86_64-linux.tar.gz zgroup
          gh release create ${GITHUB_REF_NAME} ./*.tar.gz --generate-notes
